# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.python.3.10.20.stamp: .container/compile-gcc/deps/python/url.deps .container/compile-gcc/deps/python/3.10/version.deps
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.10 .makefile/container/scripts/fetch.sh python
	touch $@

.container/compile-gcc/deps/python/3.10/hash.deps: $(FETCH_PATH)/.python.3.10.20.stamp
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.10 .makefile/container/scripts/update-hash.sh python

PREREQUISITES += .container/compile-gcc/deps/python/3.10/hash.deps

$(FETCH_PATH)/.python.3.11.15.stamp: .container/compile-gcc/deps/python/url.deps .container/compile-gcc/deps/python/3.11/version.deps
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.11 .makefile/container/scripts/fetch.sh python
	touch $@

.container/compile-gcc/deps/python/3.11/hash.deps: $(FETCH_PATH)/.python.3.11.15.stamp
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.11 .makefile/container/scripts/update-hash.sh python

PREREQUISITES += .container/compile-gcc/deps/python/3.11/hash.deps

$(FETCH_PATH)/.python.3.12.13.stamp: .container/compile-gcc/deps/python/url.deps .container/compile-gcc/deps/python/3.12/version.deps
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.12 .makefile/container/scripts/fetch.sh python
	touch $@

.container/compile-gcc/deps/python/3.12/hash.deps: $(FETCH_PATH)/.python.3.12.13.stamp
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.12 .makefile/container/scripts/update-hash.sh python

PREREQUISITES += .container/compile-gcc/deps/python/3.12/hash.deps

$(FETCH_PATH)/.python.3.13.14.stamp: .container/compile-gcc/deps/python/url.deps .container/compile-gcc/deps/python/3.13/version.deps
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.13 .makefile/container/scripts/fetch.sh python
	touch $@

.container/compile-gcc/deps/python/3.13/hash.deps: $(FETCH_PATH)/.python.3.13.14.stamp
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.13 .makefile/container/scripts/update-hash.sh python

PREREQUISITES += .container/compile-gcc/deps/python/3.13/hash.deps

$(FETCH_PATH)/.python.3.14.6.stamp: .container/compile-gcc/deps/python/url.deps .container/compile-gcc/deps/python/3.14/version.deps
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.14 .makefile/container/scripts/fetch.sh python
	touch $@

.container/compile-gcc/deps/python/3.14/hash.deps: $(FETCH_PATH)/.python.3.14.6.stamp
	M6E_DEPS_STAGE=compile-gcc M6E_SERIES=3.14 .makefile/container/scripts/update-hash.sh python

PREREQUISITES += .container/compile-gcc/deps/python/3.14/hash.deps

